// AUTO-GERADO por scripts/generate-og-meta.ts — NÃO editar à mão.
// Mapa slim pra rota edge opengraph-image.tsx (sem importar blog-data inteiro).
// Regenerar após adicionar/remover posts: `bun scripts/generate-og-meta.ts`
export type OgLook = "light" | "dark";
export const OG_META: Record<string, { t: string; look: OgLook; label: string }> = {
  "quanto-custa-marketing-cripto-brasil-2026": { t: "Quanto custa marketing cripto no Brasil em 2026", look: "light", label: "Marketing" },
  "geo-como-ser-citado-pela-ia-guia-cripto": { t: "GEO: como ser citado pela IA (ChatGPT, Perplexity, Claude) — guia para cripto", look: "light", label: "IA & Automacao" },
  "kol-marketing-fundraising-cripto-guia": { t: "KOL marketing e fundraising em cripto: o guia", look: "light", label: "Growth" },
  "marketing-cripto-guia-completo-2026": { t: "Marketing cripto em 2026: o guia completo", look: "light", label: "Marketing" },
  "como-lancar-token-tge-guia-marketing": { t: "Como lançar um token (TGE): o guia de marketing", look: "light", label: "Growth" },
  "narrativas-cripto-2026": { t: "Narrativas cripto: o que move o mercado em 2026", look: "dark", label: "Cripto" },
  "comunidade-cripto-que-nao-morre": { t: "Comunidade cripto que não morre: como construir", look: "light", label: "Growth" },
  "airdrop-programa-de-pontos-guia-marketing-cripto": { t: "Airdrop e programa de pontos: o guia de marketing cripto", look: "light", label: "Growth" },
  "infofi-kaito-atencao-novo-jogo-cripto": { t: "InfoFi e Kaito: como ganhar atenção no novo jogo cripto", look: "dark", label: "Cripto" },
  "stablecoins-rwa-marketing-onda-institucional": { t: "Stablecoins e RWA: o marketing da nova onda institucional", look: "light", label: "Marketing" },
  "como-escolher-agencia-marketing-cripto-checklist": { t: "Como escolher uma agência de marketing cripto (checklist)", look: "light", label: "Marketing" },
  "orcamento-lancamento-token-tge-custo": { t: "Orçamento de um lançamento de token (TGE): quanto custa de verdade", look: "light", label: "Growth" },
  "airdrop-quanto-alocar-supply-roi": { t: "Airdrop: quanto alocar do supply e qual o ROI real", look: "light", label: "Growth" },
  "mercado-marketing-cripto-brasil-2026": { t: "O mercado de marketing cripto no Brasil: tamanho, players e tendências 2026", look: "light", label: "Marketing" },
  "funil-growth-cripto-awareness-conversao": { t: "Funil de growth cripto: do awareness à conversão (com benchmarks)", look: "light", label: "Growth" },
  "stablecoins-rwa-tamanho-mercado-oportunidade-marketing": { t: "Stablecoins e RWA: tamanho de mercado e a oportunidade de marketing", look: "light", label: "Marketing" },
  "kol-cripto-por-tier-quanto-custa-influencer": { t: "KOL cripto por tier: quanto custa cada nível de influencer (com tabela)", look: "light", label: "Growth" },
  "retencao-comunidade-cripto-metricas-benchmarks": { t: "Retenção de comunidade cripto: métricas, benchmarks e como medir", look: "light", label: "Growth" },
  "seo-vs-geo-2026-onde-investir": { t: "SEO vs GEO em 2026: onde investir pra ser achado (Google + IA)", look: "light", label: "Marketing" },
  "neobanks-cripto-cartoes-dolar-2026": { t: "Neobanks cripto e cartões em dólar: como escolher em 2026", look: "dark", label: "Cripto" },
  "polymarket-mercados-de-previsao-licao-marketing": { t: "Polymarket: a lição de marketing dos mercados de previsão", look: "dark", label: "Cripto" },
  "kalshi-mercado-de-previsao-regulado": { t: "Kalshi: o mercado de previsão regulado e a lição de posicionamento", look: "dark", label: "Cripto" },
  "melhores-agencias-marketing-cripto-brasil-2026": { t: "As melhores agências de marketing cripto e web3 em 2026 (Brasil e mundo)", look: "light", label: "Marketing" },
  "hyperliquid-estrategia-marketing-teardown": { t: "Hyperliquid: teardown da estratégia de marketing", look: "dark", label: "Cases" },
  "agencia-boutique-vs-grande-marketing-cripto": { t: "Agência boutique vs grande pra marketing cripto", look: "light", label: "Marketing" },
  "gtm-web3-go-to-market-cripto": { t: "Go-to-market web3: framework pra lançar projeto cripto", look: "light", label: "Growth" },
  "projetos-web3-brasileiros-2026": { t: "15 projetos web3 brasileiros pra ficar de olho em 2026", look: "dark", label: "Cripto" },
  "pudgy-penguins-marketing-marca-teardown": { t: "Pudgy Penguins: como uma coleção de NFT virou marca global", look: "dark", label: "Cases" },
  "mindshare-vs-vanity-metrics-cripto": { t: "Mindshare cripto vs. vanity metrics: o que medir", look: "light", label: "Growth" },
  "branding-web3-marca-cripto-memoravel": { t: "Branding web3: como criar uma marca cripto memorável", look: "light", label: "Marketing" },
  "listing-exchange-marketing-cripto": { t: "Listagem em exchange cripto: o peso do marketing", look: "light", label: "Growth" },
  "ia-marketing-cripto-automacao-conteudo": { t: "IA no marketing cripto: automação de conteúdo e BD", look: "light", label: "IA & Automacao" },
  "como-criar-conteudo-com-ia": { t: "Como Criar Conteúdo com IA: Guia Prático para Marcas", look: "light", label: "IA & Automacao" },
  "marketing-para-startups": { t: "Marketing Digital para Startups: Estratégias que Funcionam com Pouco Budget", look: "light", label: "Marketing" },
  "automacao-marketing-2026": { t: "Automação de Marketing em 2026: Ferramentas e Estratégias", look: "light", label: "IA & Automacao" },
  "como-gerar-leads-b2b": { t: "Como Gerar Leads B2B: 10 Estratégias Comprovadas", look: "light", label: "Growth" },
  "branding-para-empresas-tech": { t: "Branding para Empresas de Tecnologia: Guia Completo", look: "light", label: "Marketing" },
  "roi-marketing-digital": { t: "Como Calcular o ROI do Marketing Digital (com Exemplos)", look: "light", label: "Marketing" },
  "copywriting-que-converte": { t: "Copywriting que Converte: Técnicas para Landing Pages e Anúncios", look: "light", label: "Marketing" },
  "seo-para-saas": { t: "SEO para SaaS: Como Rankear seu Produto no Google", look: "light", label: "Growth" },
  "community-building-web3": { t: "Community Building em Web3: Como Construir Comunidades que Crescem", look: "dark", label: "Cripto" },
  "growth-hacking-cripto": { t: "Growth Hacking para Projetos Cripto: Estratégias de Aquisição", look: "dark", label: "Cripto" },
  "regulacao-marketing-cripto-brasil-2026": { t: "Regulação cripto no Brasil e marketing: o que você pode e não pode comunicar", look: "dark", label: "Cripto" },
  "estatisticas-marketing-cripto-2026": { t: "Estatísticas de marketing cripto em 2026 que todo founder deveria saber", look: "dark", label: "Cripto" },
  "nubank-teardown-marketing-marca": { t: "Como o Nubank construiu a marca: teardown de marketing para projetos cripto", look: "dark", label: "Cases" },
  "marketing-defi-protocolo-sem-shill": { t: "Marketing de protocolo DeFi: como divulgar sem virar shill", look: "dark", label: "Cripto" },
  "pr-assessoria-imprensa-cripto-brasil": { t: "PR e assessoria de imprensa cripto no Brasil: o guia completo", look: "light", label: "Marketing" },
  "marketing-memecoin-o-que-funciona": { t: "Marketing para memecoins: o que funciona (e o que é só golpe)", look: "dark", label: "Cripto" },
  "discord-vs-telegram-comunidade-cripto": { t: "Discord vs Telegram para comunidade cripto: qual escolher em 2026", look: "light", label: "Growth" },
  "ama-cripto-guia-completo": { t: "Como fazer um AMA de cripto que gera resultado: guia passo a passo", look: "light", label: "Growth" },
  "twitter-x-crescimento-projeto-cripto": { t: "Twitter (X) para projetos cripto: o guia de crescimento orgânico", look: "light", label: "Growth" },
  "marketing-wallet-infraestrutura-cripto": { t: "Marketing para wallets e infraestrutura cripto: como comunicar produto técnico", look: "dark", label: "Cripto" },
  "roi-marketing-cripto-como-medir": { t: "Como medir o ROI do marketing cripto: as métricas que importam (e as de vaidade)", look: "dark", label: "Cripto" },
  "marketing-nft-2026-vale-a-pena": { t: "Marketing para NFT em 2026: ainda vale a pena?", look: "dark", label: "Cripto" },
  "rebranding-projeto-cripto-quando-como": { t: "Rebranding de projeto cripto: quando fazer e como não perder a comunidade", look: "dark", label: "Cripto" },
  "marketing-stablecoin-brasil": { t: "Marketing para stablecoin no Brasil: como comunicar dólar digital", look: "dark", label: "Cripto" },
  "whitepaper-litepaper-cripto-que-converte": { t: "Whitepaper e litepaper cripto: como escrever pra convencer, não pra encher linguiça", look: "dark", label: "Cripto" },
  "growth-loops-cripto-referral-quests": { t: "Growth loops em cripto: referral, quests e pontos que escalam de verdade", look: "light", label: "Growth" },
  "segredos-agencia-marketing-web3": { t: "Segredos de uma agência de marketing web3: o que a gente faz diferente por dentro", look: "light", label: "Marketing" },
  "o-que-e-agencia-marketing-cripto": { t: "O que é uma agência de marketing cripto (e quando contratar uma)", look: "dark", label: "Cripto" },
  "agencias-seo-cripto-o-que-avaliar": { t: "Agências de SEO para criptomoedas: o que avaliar antes de contratar", look: "dark", label: "Cripto" },
  "tokenomics-e-marketing-sell-buy-pressure": { t: "Tokenomics é marketing: sell/buy pressure como decisão de growth", look: "dark", label: "Cripto" },
  "developer-grants-como-gtm": { t: "Developer grants como GTM: fazer terceiros construírem por você", look: "dark", label: "Cripto" },
  "dao-marketing-crescer-reter": { t: "DAO marketing: estratégias pra crescer e reter comunidade em 2026", look: "dark", label: "Cripto" },
  "airdrop-pos-mortem-evitar-dump": { t: "Airdrop pós-mortem: como evitar o dump no dia da distribuição", look: "dark", label: "Cripto" },
  "jogo-dos-incentivos-airdrops-2026": { t: "O jogo dos incentivos: como os airdrops vão mudar em 2026", look: "dark", label: "Cripto" },
  "teardown-blast-l2-dump-tvl": { t: "Teardown Blast: o L2 que despejou o token e perdeu TVL", look: "dark", label: "Cases" },
  "teardown-lombard-points-system": { t: "Teardown Lombard: o points system que pune capital mercenário", look: "dark", label: "Cases" },
  "livro-web3-marketing-amanda-cassatt-aprendizados": { t: "O livro 'Web3 Marketing' da Amanda Cassatt: os aprendizados centrais (e o que aplica no Brasil)", look: "dark", label: "Cripto" },
  "estruturar-time-bd-growth-cripto": { t: "Como estruturar o time de BD e growth de um projeto cripto", look: "light", label: "Growth" },
  "conferencia-web3-motor-de-crescimento": { t: "Como virar uma conferência web3 em motor de crescimento full-funnel", look: "light", label: "Growth" },
  "facebook-ads-cripto-restricoes": { t: "Facebook Ads para cripto: como anunciar e contornar as restrições da Meta em 2026", look: "dark", label: "Cripto" },
  "advertising-cripto-que-converte": { t: "Estratégia de advertising cripto que converte (não só impressão)", look: "dark", label: "Cripto" },
  "web3-marketing-arte-perdida": { t: "Web3 marketing é uma arte perdida: onde os projetos erram", look: "dark", label: "Cripto" },
  "melhores-ferramentas-analytics-cripto-2026": { t: "As melhores ferramentas de analytics cripto em 2026", look: "dark", label: "Cripto" },
  "melhores-plataformas-yield-farming-2026": { t: "As melhores plataformas de yield farming em 2026 (e como avaliar risco)", look: "dark", label: "Cripto" },
  "melhores-market-makers-cripto-2026": { t: "Market makers de cripto em 2026: o que são, como escolher e a ligação com marketing", look: "dark", label: "Cripto" },
  "guia-seo-para-cripto": { t: "Guia completo de SEO para cripto e web3 (2026): do zero ao avançado", look: "dark", label: "Cripto" },
  "problemas-criticos-seo-tecnico": { t: "Problemas críticos de SEO técnico que derrubam o seu ranking (e como achar)", look: "light", label: "Marketing" },
  "auditoria-google-ads-guia": { t: "Como fazer uma auditoria de Google Ads (checklist passo a passo)", look: "light", label: "Marketing" },
  "social-media-fintech-estrategia": { t: "Estratégia de social media para fintech: confiança, compliance e conteúdo", look: "light", label: "Marketing" },
  "onde-desperdica-verba-google-ads": { t: "Onde você está desperdiçando verba no Google Ads (e como parar o vazamento)", look: "light", label: "Marketing" },
  "redesenhar-site-sem-perder-seo": { t: "Como redesenhar seu site sem perder o SEO (checklist de migração)", look: "light", label: "Marketing" },
  "por-que-seu-seo-nao-esta-funcionando": { t: "Por que o seu SEO não está funcionando (as 7 causas mais comuns)", look: "light", label: "Marketing" },
  "quanto-do-faturamento-investir-em-marketing": { t: "Quanto do faturamento investir em marketing (benchmarks por estágio e setor)", look: "light", label: "Marketing" },
  "seo-para-varejo-e-commerce": { t: "SEO para varejo e e-commerce: guia prático para vender mais no orgânico", look: "light", label: "Marketing" },
  "quanto-custa-social-media-marketing-precos": { t: "Quanto custa social media marketing no Brasil (guia de preços 2026)", look: "light", label: "Marketing" },
  "inbound-marketing-para-saas": { t: "Inbound marketing para SaaS: crescimento orgânico consistente", look: "light", label: "Marketing" },
  "alternativas-ao-google-ads-para-aquisicao": { t: "Alternativas ao Google Ads para aquisição: o que fazer quando o CPC não fecha a conta", look: "light", label: "Marketing" },
  "email-marketing-para-fintech": { t: "Email marketing para fintech: práticas que convertem (sem perder compliance)", look: "light", label: "Marketing" },
  "content-marketing-para-fintech": { t: "Content marketing para fintech: o guia completo", look: "light", label: "Marketing" },
  "influencer-marketing-para-fintech": { t: "Influencer marketing para fintech: como fazer dar certo (sem risco regulatório)", look: "light", label: "Marketing" },
  "marketing-tokenizacao-rwa-brasil": { t: "Marketing de tokenização de ativos reais (RWA) no Brasil: como vender confiança, não hype", look: "dark", label: "Cripto" },
  "como-exchanges-cripto-crescem-base-usuarios-brasil": { t: "Como corretoras e exchanges cripto crescem a base de usuários no Brasil", look: "light", label: "Growth" },
  "marketing-para-fintech-de-dolar-digital-stablecoin": { t: "Marketing para fintechs de dólar digital e stablecoin no Brasil: o guia prático", look: "light", label: "Marketing" },
  "growth-saas-infraestrutura-web3": { t: "Growth para SaaS e infraestrutura web3: como crescer quando o cliente é desenvolvedor", look: "light", label: "Growth" },
  "ia-conteudo-cripto-escalar-voz-marca": { t: "IA na produção de conteúdo cripto: como escalar sem perder a voz da marca", look: "light", label: "IA & Automacao" },
  "dao-governanca-engajamento-comunidade": { t: "Marketing de comunidade e governança: como projetos de DAO engajam de verdade", look: "dark", label: "Cripto" },
  "nft-utilidade-gaming-web3-2026": { t: "Marketing de NFT com utilidade e gaming web3 em 2026: o que sobrou depois da especulação", look: "dark", label: "Cripto" },
  "midia-e-imprensa-projetos-cripto-o-que-funciona": { t: "Assessoria de imprensa e mídia para projetos cripto no Brasil: o que funciona", look: "light", label: "Marketing" },
  "engajamento-nao-e-adocao-metricas-de-vaidade-cripto": { t: "Engajamento não é adoção: as métricas de vaidade que enganam founders cripto", look: "light", label: "Growth" },
  "marketing-de-influencia-em-fintech-como-fazer-dar-certo": { t: "Marketing de influência em fintech: como fazer dar certo (sem quebrar compliance)", look: "light", label: "Growth" },
  "anuncios-cripto-facebook-meta-compliance-targeting": { t: "Anúncios de cripto no Facebook/Meta: o que passa na revisão e como estruturar", look: "light", label: "Growth" },
  "seo-tecnico-web3-schema-glossario-paginas-comparacao": { t: "SEO técnico pra web3: schema, glossário e páginas de comparação que rankeiam", look: "light", label: "Marketing" },
  "newsletter-como-ativo-de-autoridade-cripto-modelo-not-boring": { t: "Newsletter como ativo de autoridade em cripto: o modelo Not Boring", look: "light", label: "Marketing" },
  "como-escolher-agencia-marketing-web3-guia-vetting": { t: "Como escolher uma agência de marketing web3: guia de vetting (perguntas e red flags)", look: "light", label: "Marketing" },
  "growth-de-exchange-cripto-trafego-organico-e-pago": { t: "Growth de exchange: como cripto exchanges crescem tráfego orgânico e pago", look: "light", label: "Growth" },
  "funil-bowtie-aquisicao-retencao-expansao-cripto": { t: "O funil virou bowtie: aquisição, retenção e expansão em cripto", look: "light", label: "Growth" },
  "cinco-animais-christoph-janz-ticket-define-canal": { t: "Os 5 animais de Christoph Janz: o ticket define o canal de aquisição", look: "light", label: "Growth" },
  "airdrop-retroativo-vs-proativo-qual-encaixa": { t: "Airdrop retroativo vs. proativo: qual encaixa no seu momento", look: "dark", label: "Cripto" },
  "bots-telegram-cripto-ferramentas-e-guia": { t: "Bots de Telegram pra cripto: as ferramentas que realmente ajudam (+ guia)", look: "light", label: "Growth" },
  "growth-loops-cripto-viral-conteudo-pago-incentivo": { t: "Growth loops em cripto: viral, conteúdo, pago e o loop de incentivo", look: "light", label: "Growth" },
  "teardown-ens-airdrop-identidade-governanca": { t: "Teardown ENS: o airdrop que virou identidade e engajou governança", look: "dark", label: "Cases" },
  "x-trading-floor-cripto-content-strategy-tempo-real": { t: "X é a trading floor de cripto: content strategy em tempo real", look: "light", label: "Growth" },
  "content-led-growth-motor-de-aquisicao-web3": { t: "Content-led growth: como conteúdo vira o motor de aquisição em web3", look: "light", label: "Marketing" },
  "crypto-investor-relations-confianca-de-holders": { t: "Crypto investor relations: ganhar e manter a confiança de holders", look: "light", label: "Marketing" },
  "exchange-listing-como-evento-de-gtm": { t: "Exchange listing como evento de GTM: preparar antes de listar", look: "light", label: "Growth" },
  "come-for-purpose-stay-for-community-mindset-web3": { t: "Come for the purpose, stay for the community: o mindset web3", look: "light", label: "Growth" },
  "gtm-matrix-a16z-quatro-quadrantes": { t: "A GTM Matrix da a16z: 4 quadrantes, 4 estratégias diferentes", look: "light", label: "Growth" },
  "crypto-telegram-bible-grupos-canais-promocao": { t: "2026 crypto Telegram bible: grupos, canais e promoção", look: "light", label: "Growth" },
  "como-criar-estrategia-marketing-cripto-do-zero": { t: "Como criar sua estratégia de marketing cripto do zero", look: "light", label: "Marketing" },
  "web3-marketing-guia-definitivo-2026": { t: "Web3 marketing: o guia definitivo pra 2026", look: "light", label: "Marketing" },
  "meme-coin-marketing-licoes-dos-projetos": { t: "Meme coin marketing: as lições dos projetos que deram certo", look: "light", label: "Growth" },
  "pmf-antes-de-gtm-erro-de-lancar-token-cedo": { t: "PMF vem antes de GTM: o erro de lançar token cedo demais", look: "light", label: "Growth" },
  "teardown-blur-points-farming-vs-opensea": { t: "Teardown Blur: points farming que ultrapassou a OpenSea", look: "dark", label: "Cases" },
  "crypto-promotion-2026-crescimento-on-chain": { t: "Crypto promotion em 2026: promo que gera crescimento on-chain real", look: "light", label: "Growth" },
  "founder-como-jardineiro-arquitetar-ecossistema": { t: "O founder como jardineiro: arquitetar ecossistema em vez de ditar resultado", look: "light", label: "Growth" },
  "metricas-reais-por-categoria-defi-dao-l1-l2": { t: "Métricas reais por categoria: DeFi, social DAO, game DAO e L1/L2", look: "dark", label: "Cripto" },
  "points-program-que-nao-colapsa-na-distribuicao": { t: "Como desenhar um points program que não colapsa na distribuição", look: "dark", label: "Cripto" },
  "cinco-fases-de-gtm-lunar-strategy": { t: "As 5 fases de GTM da Lunar Strategy: anatomia de um framework de lançamento", look: "light", label: "Growth" },
  "layer-de-trend-narrativa-da-vez-sem-oportunismo": { t: "Layer de trend: encaixar o projeto na narrativa da vez sem oportunismo", look: "light", label: "Growth" },
  "gtm-hibrido-plg-self-service-sales-enterprise": { t: "GTM híbrido em cripto: PLG para self-service, sales para enterprise", look: "light", label: "Growth" },
  "utility-audit-token-tem-utilidade-real": { t: "Utility audit: o token do seu projeto tem utilidade real?", look: "dark", label: "Cripto" },
  "crypto-seo-em-bear-market-construir-trafego": { t: "Crypto SEO em bear market: construir tráfego enquanto todos somem", look: "light", label: "Marketing" },
  "distribuicao-press-release-cripto-2026": { t: "Melhores serviços de distribuição de press release cripto em 2026", look: "light", label: "Growth" },
  "manufacturing-hype-wave-massa-critica-kols": { t: "Manufacturing a hype wave: massa crítica de KOLs em 24-72h", look: "light", label: "Growth" },
  "thought-leadership-data-driven-crypto-pragmatist": { t: "Thought leadership data-driven: o modelo Crypto Pragmatist", look: "light", label: "Marketing" },
  "teardown-opensea-royalties-on-chain": { t: "Teardown OpenSea: marketplace com royalties on-chain via smart contract", look: "dark", label: "Cases" },
  "nft-marketing-guide-2026": { t: "NFT marketing guide 2026: como promover ativos digitais", look: "light", label: "Growth" },
  "o-que-uma-agencia-de-marketing-web3-faz": { t: "O que uma agência de marketing web3 realmente faz", look: "light", label: "Growth" },
  "giving-money-away-ciencia-dos-airdrops": { t: "\"Giving money away is harder than it seems\": a ciência dos airdrops", look: "dark", label: "Cripto" },
  "google-ads-para-fintech-alta-performance": { t: "Google Ads para fintech: como montar campanhas de alta performance", look: "light", label: "Growth" },
  "guia-de-kol-2026-estruturar-campanha-influencer": { t: "Guia de KOL 2026: como estruturar uma campanha de influenciadores em cripto", look: "light", label: "Growth" },
  "blog-cripto-que-rankeia-arquitetura-seo-aeo": { t: "Blog cripto que rankeia: arquitetura de conteúdo para SEO e AEO", look: "light", label: "Marketing" },
  "email-marketing-fintech-cripto-9-praticas": { t: "Email marketing para fintech e cripto: 9 práticas que convertem", look: "light", label: "Marketing" },
  "press-release-cripto-que-a-midia-publica": { t: "Como escrever press release cripto que a mídia realmente publica", look: "light", label: "Growth" },
  "gtm-cripto-vs-saas-quadro-comparativo": { t: "GTM cripto vs. SaaS: o quadro comparativo definitivo", look: "light", label: "Growth" },
  "guia-de-token-distribution-points-airdrop-liquidity": { t: "Guia de token distribution: points, airdrop, liquidity mining", look: "dark", label: "Cripto" },
  "comunicar-tokenomics-sem-soar-como-esquema": { t: "Como comunicar tokenomics sem soar como esquema", look: "dark", label: "Cripto" },
  "web3-gtm-strategy-analytics-on-chain": { t: "Web3 GTM strategy: o guia com foco em analytics on-chain", look: "light", label: "Growth" },
  "playbook-de-lancamento-2026-checklist-tge": { t: "Playbook de lançamento 2026: checklist completo de TGE", look: "light", label: "Growth" },
  "pumpfun-o-lancamento-que-virou-entretenimento": { t: "Pump.fun: o lançamento que virou entretenimento (e a conta que vem junto)", look: "dark", label: "Cases" },
  "kaito-o-mindshare-virou-token": { t: "Kaito: o mindshare virou token (e o token virou risco)", look: "dark", label: "Cases" },
  "arbitrum-o-airdrop-que-virou-padrao-de-mercado": { t: "Arbitrum: o airdrop que virou padrão de mercado (e o drama que veio junto)", look: "dark", label: "Cases" },
  "base-distribuicao-como-vantagem-desleal": { t: "Base: distribuição como vantagem desleal (a marca-mãe que distribui a marca-filha)", look: "dark", label: "Cases" },
  "solana-a-ressurreicao": { t: "Solana: a ressurreição (como uma chain dada como morta voltou pela comunidade)", look: "dark", label: "Cases" },
  "berachain-comunidade-e-memes-antes-do-produto": { t: "Berachain: comunidade e memes antes do produto (e a conta que veio depois)", look: "dark", label: "Cases" },
  "uniswap-o-airdrop-que-escreveu-o-manual": { t: "Uniswap: o airdrop que escreveu o manual (e a conta que demorou cinco anos)", look: "dark", label: "Cases" },
  "optimism-financiamento-de-bem-publico-posicionamento-de-marca": { t: "Optimism: como transformar financiamento de bem público em posicionamento de marca", look: "dark", label: "Cases" },
  "tron-justin-sun-marketing-de-atencao-a-qualquer-custo": { t: "TRON e Justin Sun: o marketing de atenção a qualquer custo (e a conta que vem junto)", look: "dark", label: "Cases" },
  "story-protocol-marketar-conceito-abstrato-narrativa-do-ano": { t: "Story Protocol: como marketar um conceito abstrato e virar narrativa do ano", look: "dark", label: "Cases" },
  "incentivos-de-token-que-duram": { t: "Incentivos de token que duram: desenhando pra reter, não farmar", look: "dark", label: "Cripto" },
  "bitcoin-poder-de-comunidade": { t: "Bitcoin: por que deu certo sem marketing, sem empresa e sem dono", look: "dark", label: "Cripto" },
  "hyperliquid-airdrop-sem-vc": { t: "Hyperliquid: o airdrop bilionário sem VC e sem KOL pago", look: "dark", label: "Cripto" },
  "notcoin-ton-telegram": { t: "Notcoin e Hamster Kombat: como o Telegram virou a maior máquina de aquisição da cripto (e por que isso não basta)", look: "dark", label: "Cripto" },
  "polymarket-produto-como-midia": { t: "Polymarket: o produto que virou mídia na eleição americana", look: "dark", label: "Cripto" },
  "friendtech-hype-sem-retencao": { t: "Friend.tech: a ascensão e o sumiço, ou por que hype não é retenção", look: "dark", label: "Cripto" },
  "ethena-pontos-e-yield": { t: "Ethena: como vender um basis trade de hedge fund pra varejo chamando de \"dólar da internet\"", look: "dark", label: "Cripto" },
  "celestia-engenharia-de-narrativa": { t: "Celestia: como se inventa uma narrativa e se torna líder da categoria", look: "dark", label: "Cripto" },
  "jupiter-airdrop-como-dao": { t: "Jupiter: o airdrop que construiu uma DAO em vez de virar saída de liquidez", look: "dark", label: "Cripto" },
  "por-que-airdrops-funcionam": { t: "Por que airdrops funcionam (e se ainda funcionam em 2026)", look: "light", label: "Growth" },
  "narrativas-cripto-ao-longo-dos-anos": { t: "Narrativas cripto ao longo dos anos: o que cada ciclo ensina de marketing", look: "dark", label: "Cripto" },
  "proximas-narrativas-cripto": { t: "5 próximas narrativas cripto (e como se posicionar antes da onda)", look: "light", label: "Growth" },
  "circle-usdc-compliance-como-marca": { t: "Circle e o USDC: como a compliance virou a marca (e levou a empresa ao IPO)", look: "dark", label: "Cripto" },
  "ondo-finance-gtm-de-rwa-institucional": { t: "Ondo Finance: o GTM de RWA que fala a língua do banco, não do degen", look: "dark", label: "Cripto" },
  "worldcoin-marketing-de-produto-polemico": { t: "Worldcoin: como marketar um produto que assusta as pessoas", look: "dark", label: "Cripto" },
  "virtuals-protocol-ai-agents-como-marca": { t: "Virtuals Protocol: quando o agente de IA vira a marca e a narrativa", look: "dark", label: "Cripto" },
  "tether-a-marca-mais-lucrativa-que-nao-faz-marketing": { t: "Tether: a empresa mais lucrativa do cripto que quase não faz marketing", look: "dark", label: "Cripto" },
  "como-rodar-airdrop-que-retem": { t: "Como rodar um airdrop que retém (e não vira só saída de liquidez)", look: "dark", label: "Cripto" },
  "pontos-o-playbook-2024-2026": { t: "Pontos: o playbook de 2024 a 2026 e quando ele para de funcionar", look: "dark", label: "Cripto" },
  "geo-ai-seo-aparecer-no-chatgpt": { t: "GEO e AI-SEO: como seu projeto cripto aparece quando perguntam pro ChatGPT", look: "dark", label: "Cripto" },
  "metricas-de-marketing-cripto-valor-vs-vaidade": { t: "Métricas de marketing cripto: o que medir de verdade (valor vs vaidade)", look: "dark", label: "Cripto" },
  "marketing-cripto-no-brasil-2026": { t: "Marketing cripto no Brasil em 2026: o que muda e o que continua igual", look: "dark", label: "Cripto" },
  "solana-playbook-ecossistema-2026": { t: "Playbook Solana 2026: o ecossistema, a tese e as oportunidades", look: "dark", label: "Cripto" },
  "playbook-lancamento-token-tge": { t: "Playbook de Lançamento de Token (TGE): do pré-hype ao pós-listagem", look: "dark", label: "Cripto" },
  "gtm-web3-quatro-stakeholders": { t: "GTM em web3 não é GTM de SaaS: os 4 stakeholders que mudam tudo", look: "light", label: "Growth" },
  "gtm-cripto-estrategia-que-funciona": { t: "Como construir uma estratégia de go-to-market cripto que funciona", look: "light", label: "Growth" },
  "positioning-april-dunford-cripto": { t: "Positioning primeiro: o método April Dunford aplicado a cripto", look: "light", label: "Growth" },
  "airdrop-trap-estrategia-token": { t: "A Airdrop Trap: por que a maioria das estratégias de token falha", look: "light", label: "Growth" },
  "reddit-marketing-cripto": { t: "Reddit marketing para projetos cripto: o que funciona e o que não", look: "light", label: "Growth" },
  "crypto-wallet-marketing-carteira-ativa": { t: "Crypto wallet marketing: de instalação para carteira ativa", look: "light", label: "Growth" },
  "onchain-attribution-marketing-2026": { t: "Onchain attribution: medindo marketing cripto de verdade em 2026", look: "dark", label: "Cripto" },
  "projetos-cripto-usuarios-overnight": { t: "Por que alguns projetos cripto atraem milhares de usuários da noite pro dia", look: "light", label: "Growth" },
  "branding-cripto-mercado-cetico": { t: "Branding num mercado cético: como cripto constrói confiança pela prova", look: "light", label: "Growth" },
  "token-launch-marketing-playbook-completo": { t: "Token launch marketing: o playbook completo de lançamento", look: "light", label: "Growth" },
  "icp-projeto-cripto": { t: "ICP em cripto: por que \"todo holder\" não é um público, é uma desculpa", look: "light", label: "Growth" },
  "narrative-marketing-ciclo": { t: "Colar o projeto na narrativa da vez sem virar o oportunista que o mercado despreza", look: "light", label: "Growth" },
  "points-programs-retencao": { t: "Points program que retém vs. que destrói: por que a Lombard segurou e a Blast desabou", look: "dark", label: "Cripto" },
  "guia-crypto-token-marketing": { t: "Crypto token marketing: o guia da Kaleidos da narrativa ao pós-listagem", look: "dark", label: "Cripto" },
  "airdrop-marketing-anti-sybil": { t: "Airdrop marketing anti-Sybil: como atrair usuário real e não farmer", look: "dark", label: "Cripto" },
  "aeo-cripto-respostas-ia": { t: "AEO pra cripto: como ser a resposta que a IA dá (e não só o link que ela ignora)", look: "light", label: "IA & Automacao" },
  "ser-citado-chatgpt-perplexity-gemini": { t: "Como virar a fonte que o ChatGPT cita: o passo a passo de AEO pra projeto cripto", look: "light", label: "IA & Automacao" },
  "teardown-compound-liquidity-mining": { t: "Teardown Compound: o token que resolveu o problema da galinha e do ovo da liquidez", look: "dark", label: "Cases" },
  "crypto-press-release-2026": { t: "Crypto press release em 2026: como escrever um que a imprensa publica (com templates)", look: "light", label: "Growth" },
  "ethereum-crise-de-narrativa": { t: "Ethereum tinha o melhor produto e perdeu a narrativa: o que isso ensina sobre posicionamento", look: "light", label: "Growth" },
  "chainlink-integracao-como-marketing": { t: "Chainlink: como transformar cada integração em marketing (o playbook B2B do cripto)", look: "dark", label: "Cases" },
  "depin-marketing-dois-lados": { t: "Marketing de DePIN: token traz oferta, mas ninguém consegue subsidiar demanda pra sempre", look: "light", label: "Growth" },
  "eigenlayer-restaking-categoria": { t: "EigenLayer: como criar uma categoria bilionária e quase queimar a comunidade no airdrop", look: "dark", label: "Cases" },
  "aerodrome-liquidez-como-marketing": { t: "Aerodrome: como virar a praça central de liquidez de um ecossistema inteiro", look: "dark", label: "Cases" },
  "x-twitter-growth-cripto": { t: "Growth orgânico no X para cripto: o playbook de conversa que o algoritmo premia", look: "light", label: "Growth" },
  "farcaster-frames-formato-viral": { t: "Farcaster: como um formato novo virou loop de crescimento (e por que o pico não segurou)", look: "dark", label: "Cases" },
  "telegram-community-engine-cripto": { t: "Engine de comunidade no Telegram: como construir o grupo cripto que não vira spam", look: "light", label: "Growth" },
  "discord-retencao-cripto": { t: "O Discord que não morre: como construir comunidade cripto que sobrevive ao mint", look: "light", label: "Growth" },
  "pendle-marketplace-de-narrativa": { t: "Pendle: como virar o mercado onde toda narrativa quente é precificada", look: "dark", label: "Cases" },
  "morpho-infraestrutura-invisivel": { t: "Morpho: como crescer sendo a infraestrutura invisível por trás de uma marca gigante", look: "dark", label: "Cases" },
  "quest-platforms-galxe-zealy-roi": { t: "Plataformas de quest (Galxe, Zealy, Layer3): o ROI real por trás dos números gigantes", look: "light", label: "Growth" },
  "jito-mev-como-produto": { t: "Jito: como transformar um conceito abstrato (MEV) em produto que as pessoas querem segurar", look: "dark", label: "Cases" },
  "twitter-spaces-ama-cripto": { t: "Twitter Spaces e AMAs que convertem: o playbook de áudio ao vivo pra cripto", look: "light", label: "Growth" },
  "programa-embaixadores-cripto": { t: "Programa de embaixadores cripto: como escalar comunidade sem criar exército de mercenário", look: "light", label: "Growth" },
  "sui-pedigree-e-comunidade": { t: "Sui: como pedigree abre a porta e a relação com a comunidade decide se você fica", look: "dark", label: "Cases" },
  "meme-marketing-cripto-metodo": { t: "Meme marketing com método: como usar cultura sem virar a próxima moeda que zerou", look: "light", label: "Growth" },
  "monad-comunidade-antes-do-mainnet": { t: "Monad: como construir uma comunidade e uma cultura de meme antes de existir produto", look: "dark", label: "Cases" },
  "blur-vampire-attack-royalties": { t: "Blur: como usar incentivo agressivo pra destronar o líder (e o preço disso)", look: "dark", label: "Cases" },
  "referral-loops-virais-cripto": { t: "Loops virais e referral em cripto: a mecânica que faz o usuário trazer o próximo", look: "light", label: "Growth" },
  "aave-rebrand-ghost-confianca": { t: "Aave: como um rebrand e uma marca de confiança viraram o maior fosso do DeFi", look: "dark", label: "Cases" },
  "testnet-mainnet-marketing": { t: "Marketing de testnet para mainnet: como não perder na largada os milhões que você atraiu", look: "light", label: "Growth" },
  "exchange-listing-marketing": { t: "Marketing do listing em exchange: como não desperdiçar o único dia em que todos olham", look: "light", label: "Growth" },
  "lido-liquid-staking-narrativa": { t: "Lido: como definir uma categoria e depois virar refém da própria narrativa de descentralização", look: "dark", label: "Cases" },
  "category-design-cripto-nomear-mercado": { t: "Criar categoria em cripto: como nomear um mercado novo e virar rei dele", look: "light", label: "Growth" },
  "marketing-listing-exchange-ieo": { t: "Marketing de listing e IEO: o dia do anúncio não é a estratégia, é o teste dela", look: "light", label: "Growth" },
  "gtm-rwa-imobiliario-credito": { t: "GTM de RWA além do Ondo: como vender crédito e imóvel tokenizado sem público pronto", look: "light", label: "Growth" },
  "gtm-stablecoin-nova-competir": { t: "GTM de stablecoin nova: como competir num mercado onde dois nomes têm 88%", look: "light", label: "Growth" },
  "metricas-comunidade-cripto": { t: "Métricas de comunidade em cripto: as que importam e as que só enganam o founder", look: "light", label: "Growth" },
  "storytelling-founder-cripto": { t: "Storytelling de founder em cripto: quando o rosto vira ativo e quando vira risco", look: "light", label: "Growth" },
  "gtm-b2b-infra-web3": { t: "GTM B2B em web3: como vender infraestrutura para outros protocolos e devs", look: "light", label: "Growth" },
  "seo-tecnico-dapps-web3": { t: "SEO técnico para dapps web3: por que seu app é invisível para o Google (e para a IA)", look: "light", label: "Growth" },
  "earned-media-pr-cripto-confianca": { t: "Earned media em cripto: por que a cobertura que você não pagou vale mais que a que pagou", look: "light", label: "Growth" },
  "comunidade-real-vs-hype-train": { t: "Comunidade real vs. hype train: como saber a diferença antes de queimar caixa", look: "light", label: "Growth" },
  "kol-crypto-guide-2026-distribuicao": { t: "KOL crypto guide 2026: como usar influencer como parceiro de distribuição (não como outdoor)", look: "light", label: "Growth" },
  "verificar-kol-cripto-onchain": { t: "Como verificar um KOL cripto de verdade: audite a wallet, não os seguidores", look: "light", label: "Growth" },
  "crypto-ad-networks-2026": { t: "Top crypto ad networks em 2026: onde vale a pena anunciar (e onde é dinheiro jogado fora)", look: "light", label: "Growth" },
  "crypto-google-ads-compliant": { t: "Crypto Google Ads: como rodar campanha performática que passa na revisão", look: "light", label: "Growth" },
  "thought-leadership-web3-autoridade": { t: "Thought leadership em web3: como virar autoridade num mercado que só grita", look: "light", label: "Marketing" },
  "crypto-presale-marketing-tracao": { t: "Crypto presale marketing: como construir tração antes do lançamento (e não virar mais uma que falha)", look: "light", label: "Growth" },
  "branding-cripto-construir-confianca": { t: "Branding em cripto: por que confiança é o produto (não a marca)", look: "light", label: "Growth" },
  "comunidade-cripto-que-converte": { t: "Seu Discord tem 80 mil membros e nenhuma comunidade", look: "light", label: "Growth" },
  "funil-aquisicao-produtos-cripto": { t: "Funil de aquisição cripto: do anúncio à carteira", look: "light", label: "Growth" },
  "growth-exchanges-fintech-cripto": { t: "Pare de pagar por clique: o CAC que importa em exchange cripto é o depositante que fica", look: "light", label: "Growth" },
  "influenciadores-campanhas-web3": { t: "KOL em web3: como contratar influenciador sem virar réu", look: "light", label: "Growth" },
  "narrativas-de-mercado-cripto": { t: "Quando a narrativa chega no seu feed, ela já morreu", look: "light", label: "Growth" },
  "playbook-conteudo-autoridade-web3": { t: "No cripto, ninguém confia em você (e como virar autoridade mesmo assim)", look: "light", label: "Growth" },
  "playbook-lancamento-projeto-web3": { t: "Como lançar um token web3 sem ver o gráfico sangrar na primeira semana", look: "light", label: "Growth" },
  "seo-para-projetos-cripto": { t: "SEO cripto em 2026: por que 62% dos projetos financiados são invisíveis", look: "light", label: "Growth" },
  "tokenomics-e-marketing": { t: "Sua tokenomics é seu maior ativo de marketing (e ninguém no time de growth escreveu ela)", look: "light", label: "Growth" },
};
